// Method-level inventory of the Platform HTTP security boundary. Every route
// is explicit so adding a new Stage 1 API requires an intentional auth class.
export const stage1RouteInventory = [
  ['GET', '/api/health', 'public'],
  ['GET', '/api/readiness', 'public'],
  ['POST', '/api/company/auth/bootstrap', 'capability'],
  ['POST', '/api/company/auth/bootstrap/complete', 'capability'],
  ['POST', '/api/company/auth/bootstrap/retry', 'capability'],
  ['POST', '/api/company/auth/session', 'public-login'],
  ['DELETE', '/api/company/auth/session', 'public-idempotent-logout'],
  ['GET', '/api/company/support/tickets', 'employee'],
  ['GET', '/api/cron/native-maintenance', 'cron'],
  ['POST', '/api/cron/native-operations', 'cron'],
  ['POST', '/api/hub-agent/operator-session/attempt', 'machine'],
  ['POST', '/api/hub-agent/operator-session/consume', 'machine'],
  ['POST', '/api/hub-agent/support/v2/proof', 'machine'],
  ['POST', '/api/hub-agent/support/v2/redeem', 'machine'],
  ['POST', '/api/hub-agent/support/v2/revocation', 'machine'],
  ['POST', '/api/hub-agent/support/v2/status', 'machine'],
  ['POST', '/api/hub-agent/token-state', 'machine'],
  ['POST', '/api/hub-agent/v2/claim/resolver/challenge', 'machine'],
  ['POST', '/api/hub-agent/v2/credentials/acknowledge', 'machine'],
  ['POST', '/api/hub-agent/v2/credentials/activate', 'machine'],
  ['POST', '/api/hub-agent/v2/heartbeat', 'machine'],
  ['POST', '/api/hub-agent/v2/pairing/acknowledge', 'manufacturing-or-machine'],
  ['POST', '/api/hub-agent/v2/pairing/challenge', 'manufacturing-or-machine'],
  ['POST', '/api/hub-agent/v2/pairing/cloud-url', 'machine'],
  ['POST', '/api/hub-agent/v2/pairing/prove', 'manufacturing-or-machine'],
  ['POST', '/api/hub-agent/v2/pairing/register', 'signed-manufacturing-bootstrap'],
  ['POST', '/api/hub-agent/v2/pairing/reservation', 'machine'],
  ['POST', '/api/installer/home-support/homes/:homeId/installation/complete', 'employee'],
  ['POST', '/api/installer/home-support/homes/:homeId/os-access/launch', 'employee'],
  ['POST', '/api/installer/home-support/homes/:homeId/os-access/revoke', 'employee'],
  ['POST', '/api/installer/home-support/homes/:homeId/os-access/rotate', 'employee'],
  ['GET', '/api/installer/home-support/homes/:homeId/os-access/status', 'employee'],
  ['POST', '/api/installer/hubs/:hubInstallationId/claim-resolver/replace', 'employee'],
  ['POST', '/api/installer/hubs/:hubInstallationId/cloudflare/reserve', 'employee'],
  ['POST', '/api/installer/hubs/provision', 'employee'],
  ['GET', '/api/installer/workflows', 'employee'],
  ['POST', '/api/installer/workflows', 'employee'],
  ['POST', '/api/internal/stage1/claim', 'contract-secret'],
  ['POST', '/api/v2/auth/session', 'public-login'],
  ['DELETE', '/api/v2/auth/session', 'customer'],
  ['POST', '/api/v2/hub-sessions', 'customer'],
  ['POST', '/api/v2/offline-authorisations', 'customer'],
  ['DELETE', '/api/v2/offline-authorisations', 'customer'],
  ['POST', '/api/v2/security/step-up/challenge', 'customer'],
  ['DELETE', '/api/v2/security/step-up/challenge', 'customer'],
  ['POST', '/api/v2/security/step-up/consume', 'customer'],
  ['POST', '/api/v2/security/step-up/issue', 'customer'],
  ['GET', '/api/v2/support/notifications', 'customer'],
  ['POST', '/api/v2/support/tickets/:ticketId/access-requests/:requestId/approve', 'customer'],
  ['POST', '/api/v2/support/tickets/:ticketId/access-requests/:requestId/issue', 'employee'],
  ['POST', '/api/v2/support/tickets/:ticketId/access-requests/:requestId/revoke', 'employee'],
  ['POST', '/api/v2/support/tickets/:ticketId/access-requests', 'employee'],
  ['POST', '/api/v2/support/tickets/:ticketId', 'customer'],
  ['POST', '/api/v2/support/tickets', 'customer'],
  ['DELETE', '/api/v2/trusted-devices/:trustedDeviceId', 'customer'],
];

export const protectedStage1Routes = stage1RouteInventory.filter(([, , auth]) => !['public', 'public-login', 'capability', 'signed-manufacturing-bootstrap'].includes(auth));
