// Architecture: Active Dinodia module prisma.config.ts; document its role here while preserving the existing runtime and cross-repository contracts.

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//jnwe
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
    directUrl: env("DIRECT_URL"),
  },
});
